# server:
#   port: 9000
eureka:
  client:
    service-url:
      default-zone: http://EUREKA-REGISTRY
spring:    
  cloud:
    gateway:
      routes:
       - id: emailApi
         uri: lb://EMAIL-API
         predicates:
          - Path=/** 
